name: 'My custom composite action with env'
description: 'testing env'

inputs:
  in:
    description: "the value to greet"
    required: false
  cpu:
    description: "cpu value"
    required: false

outputs:
  out:
    description: output
    value: ${{ steps.out.outputs.out }}

runs:
  using: 'composite'
  steps:
    - name: Loop through environment variables
      shell: bash
      id: res
      run: |
        CPU-STRING=""
        if [[ "${{ inputs.cpu }}" != "" ]] ; then
          CPU-STRING="--cpu ${{ inputs.cpu }}"
          echo "cpu = "
        else
          echo "inputs.cpu is empty"
        fi
        echo "cpu=$CPU_STRING" >> "$GITHUB_OUTPUT"

        IFS=$'\n' # Set the Internal Field Separator to newline
        INPUT_VALUES=(${{ inputs.in }}) # Split input values by newline
        for value in "${INPUT_VALUES[@]}"; do
          echo "Processing value: $value"
          # Perform your action for each value here
        done

    - name: step 2
      shell: bash
      run: |
        echo ${{ steps.res.outputs.cpu }}