name: 'My custom composite action with env'
description: 'testing env'

inputs:
  in:
    description: "the value to greet"
    required: false
  cpu:
    description: "cpu value"
    required: false

outputs:
  out:
    description: output
    value: ${{ steps.out.outputs.out }}

runs:
  using: 'composite'
  steps:
    - name: Loop through environment variables
      shell: bash
      id: res
      run: |
     
        if [[ "${{ inputs.cpu }}" != "" ]] ; then
          echo "cpu=--cpu ${{ inputs.cpu }}" >> "$GITHUB_OUTPUT"
        else
          echo "inputs.cpu is empty"
          echo "cpu=" >> "$GITHUB_OUTPUT"
        fi

        IFS=$'\n' # Set the Internal Field Separator to newline
        INPUT_VALUES=(${{ inputs.in }}) # Split input values by newline
        for value in "${INPUT_VALUES[@]}"; do
          echo "Processing value: $value"
          # Perform your action for each value here
        done

    - name: step 2
      shell: bash
      run: |
        echo "value is: ${{ steps.res.outputs.cpu }}"