name: 16 composite

on:
    push:
        branches: 
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v2
            - name: hello
              id: hello
              uses: ./.github/actions/my-action
              with: 
                name: Luke
            - name: outval
              run: echo ${{ steps.hello.outputs.out }}
    js:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v2
            - name: JS Action
              id: js
              uses: ./.github/actions/my-js-action
              with:
                name: Gandalf
                age: 2345
            - name: js out
              run: echo ${{ steps.js.outputs.username }}

    docker:
      runs-on: ubuntu-latest
      steps:
        - name: Get Code
          uses: actions/checkout@v2
          id: docker
        - name: Docker Action
          id: doc
          uses: ./.github/actions/my-docker-action
          with:
            name: Gandalf
            age: 2345
        - name: docker out
          run: echo ${{ steps.doc.outputs.username }}
