name: Multiple Jobs

on:

  push:

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Get Source Code
        uses: actions/checkout@v3

      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm --version

      - name: Run Tests
        run: node --version
        
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Get Source Code
        uses: actions/checkout@v3

      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Build
        run: echo "building using $(node --version)"

      - name: Deploy
        run: echo "deploying to server"
