# This is a basic workflow to help you get started with Actions

name: Example

on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "init"
  step-1:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Run a one-line script
        run: echo "Step 1"
  step-2:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Run a one-line script
        run: echo "Run Step 2"
  step-3:
    runs-on: ubuntu-latest
    needs: step-2
    steps:
      - name: Run a one-line script
        run: echo "Run Step 3"

  
