name: 'My custom composite action'
description: 'do some magic'
inputs:
  name:
    description: "the value to greet"
    required: true
runs:
  using: 'composite'
  steps:
    - name: Hello
      run: echo "Hello ${{ inputs.name }}"
      shell: bash