name: 'My custom composite action'
description: 'do some magic'
inputs:
  name:
    description: "the value to greet"
    required: true
outputs:
  out:
    description: output
    value: ${{ steps.out}}
runs:
  using: 'composite'
  steps:
    - name: Hello
      run: echo "Hello ${{ inputs.name }}"
      shell: bash
    - name: out
      id: out
      shell: bash
      run: echo "out=asdfasdfasdf" >> $GITHUB_OUTPUT