name: Matrix
on:
    push:
        branches: [ master ]
jobs:
    build:
        strategy:
          matrix:
            node-version: [16, 18, 20]

        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v2
            - name: Install Nodejs
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: echo "npm install"
            - name: Build Project
              run: node --version