name: Reusable Deploy

on:
    workflow_call:
        inputs:
            name:
                description: your name
                required: false
                default: World
                type: string
        secrets:
            some-secret:
                required: false
        outputs:
            result:
                description: my return value
                value: ${{ jobs.deploy.outputs.result }}
                
jobs:
    deploy:
        outputs:
            result: ${{ steps.result.outputs.result }}
        runs-on: ubuntu-latest
        steps:
            - name: Output 
              run: echo "Hello, ${{ inputs.name }}!"
            - name: return 
              id: result
              run: echo "result=Hello, ${{ inputs.name }}!" >> "$GITHUB_OUTPUT"