name: 15 containers services

on:
    push:
        branches: 
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        services:
            nginx:
                image: nginx:stable
                ports:
                    - 8080:80
                
        steps:
            - name: hello
              run: curl nginx:8080