name: event

on:
  pull_request:
    types:
      - opened
    branches:
      - master
      - 'dev-*' #dev-new
      - 'feat/**' #feat/new/btton

  push:
    branches:
      - master
      - 'dev-*' #dev-new
      - 'feat/**' #feat/new/btton
    branches-ignore:
      - 'test*'
    paths-ignore:
      - 'mypath/*'
  
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
